import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import {useRouter} from 'next/router'
import {Header, Footer} from '@features/layout'
import {useAuth} from '@features/auth'
import styles from './List.module.css'


const CreateCalculation: NextPage = () => {
  const router = useRouter()
  const auth = useAuth()
  React.useEffect(() => {
    if (!auth || !auth.session) {
      router.push('/')
    }
  }, [auth, router])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        Создание расчета
      </main>

      <Footer />
    </div>
  )
}

export default CreateCalculation
