import React, {ChangeEvent} from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

type FeeValue = number
interface EletricityTarrif {
  fee1: {
    t1: FeeValue
  },
  fee2: {
    t1: FeeValue,
    t2: FeeValue
  },
  fee3: {
    t1: FeeValue,
    t2: FeeValue,
    t3: FeeValue
  }
}

interface Tarrifs {
  country: string,
  city: string,
  fees: {
    coldWater: FeeValue,
    hotWater: FeeValue,
    drainage: FeeValue,
    gasCooker: EletricityTarrif,
    electricCooker: EletricityTarrif,
  }
}
const apiResponse: Tarrifs = {
  country: 'russia',
  city: 'moscow',
  fees: {
    coldWater: 43.57,
    hotWater: 211.67,
    drainage: 32.02,
    gasCooker: {
      fee1: {
        t1: 5.92
      },
      fee2: {
        t1: 6.81,
        t2: 2.48
      },
      fee3: {
        t1: 7.10,
        t2: 5.92,
        t3: 2.48
      }
    },
    electricCooker: {
      fee1: {
        t1: 5.15
      },
      fee2: {
        t1: 5.92,
        t2: 1.74
      },
      fee3: {
        t1: 6.18,
        t2: 5.15,
        t3: 1.74
      }
    }
  }
}

const Home: NextPage = () => {
  const tariffs = apiResponse
  const [hotWaterPrev, setHotWaterPrev] = React.useState('')
  const [hotWaterCurrent, setHotWaterCurrent] = React.useState('488.13')
  const handleWaterPrevChange = (e: ChangeEvent<HTMLInputElement>) => setHotWaterPrev(e.target.value)
  const handleWaterCurrentChange = (e: ChangeEvent<HTMLInputElement>) => setHotWaterCurrent(e.target.value)

  const [coldWaterPrev, setColdWaterPrev] = React.useState('')
  const [coldWaterCurrent, setColdWaterCurrent] = React.useState('306.91')
  const handleColdWaterPrevChange = (e: ChangeEvent<HTMLInputElement>) => setColdWaterPrev(e.target.value)
  const handleColdWaterCurrentChange = (e: ChangeEvent<HTMLInputElement>) => setColdWaterCurrent(e.target.value)

  const [electricityT1Prev, setElectricityT1Prev] = React.useState('')
  const [electricityT1Current, setElectricityT1Current] = React.useState('3382.41')
  const handleElectricityT1PrevChange = (e: ChangeEvent<HTMLInputElement>) => setElectricityT1Prev(e.target.value)
  const handleElectricityT1CurrentChange = (e: ChangeEvent<HTMLInputElement>) => setElectricityT1Current(e.target.value)

  const [electricityT2Prev, setElectricityT2Prev] = React.useState('')
  const [electricityT2Current, setElectricityT2Current] = React.useState('2403.53')
  const handleElectricityT2PrevChange = (e: ChangeEvent<HTMLInputElement>) => setElectricityT2Prev(e.target.value)
  const handleElectricityT2CurrentChange = (e: ChangeEvent<HTMLInputElement>) => setElectricityT2Current(e.target.value)

  const [electricityT3Prev, setElectricityT3Prev] = React.useState('')
  const [electricityT3Current, setElectricityT3Current] = React.useState('9349.74')
  const handleElectricityT3PrevChange = (e: ChangeEvent<HTMLInputElement>) => setElectricityT3Prev(e.target.value)
  const handleElectricityT3CurrentChange = (e: ChangeEvent<HTMLInputElement>) => setElectricityT3Current(e.target.value)
  const cookerType = 'eletricity'
  const eletricityRateNumber = 3
  const fees = selectFees({cookerType, tariffs})
  const total = calculateCommunal({
    hotWater: {
      previous: Number(hotWaterPrev),
      current: Number(hotWaterCurrent),
    },
    coldWater: {
      previous: Number(coldWaterPrev),
      current: Number(coldWaterCurrent),
    },
    electricity: {
      t1: {
        previous: Number(electricityT1Prev),
        current: Number(electricityT1Current),
      },
      t2: {
        previous: Number(electricityT2Prev),
        current: Number(electricityT2Current),
      },
      t3: {
        previous: Number(electricityT3Prev),
        current: Number(electricityT3Current),
      },
    }
  }, fees, eletricityRateNumber)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://kommune.io">Kommune!</a>
        </h1>

        <p className={styles.description}>
          This app will help you calculate communal payments
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Hot Water</h2>
            <form action="" method="">
              <input type="text" placeholder="previous" value={hotWaterPrev} onChange={handleWaterPrevChange} />
              <input type="text" placeholder="current" value={hotWaterCurrent} onChange={handleWaterCurrentChange} />
            </form>
          </div>
          <div className={styles.card}>
            <h2>Cold Water</h2>
            <form action="" method="">
              <input type="text" placeholder="previous" value={coldWaterPrev} onChange={handleColdWaterPrevChange} />
              <input type="text" placeholder="current" value={coldWaterCurrent} onChange={handleColdWaterCurrentChange} />
            </form>
          </div>
          <div className={styles.card}>
            <h2>Electricity</h2>
            <form action="" method="">
              <p>
                <input type="text" placeholder="t1 previous" value={electricityT1Prev} onChange={handleElectricityT1PrevChange} />
                <input type="text" placeholder="t1 current" value={electricityT1Current} onChange={handleElectricityT1CurrentChange} />
              </p>
              <p>
                <input type="text" placeholder="t2 previous" value={electricityT2Prev} onChange={handleElectricityT2PrevChange} />
                <input type="text" placeholder="t2 current" value={electricityT2Current} onChange={handleElectricityT2CurrentChange} />
              </p>
              <p>
                <input type="text" placeholder="t3 previous" value={electricityT3Prev} onChange={handleElectricityT3PrevChange} />
                <input type="text" placeholder="t3 current" value={electricityT3Current} onChange={handleElectricityT3CurrentChange} />
              </p>
            </form>
          </div>

          <div className={`${styles.card} ${styles.total}`}>
            <h2>Total: {total}</h2>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://kommune.io"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

interface Values {
  previous: number,
  current: number
}

interface MeterReadings {
  hotWater: Values,
  coldWater: Values,
  electricity: {
    t1: Values,
    t2: Values,
    t3: Values,
  }
}

interface CalcTarrifs {
  coldWater: FeeValue,
  hotWater: FeeValue,
  drainage: FeeValue,
  eletricity: EletricityTarrif
}
function calculateCommunal(meterReadings: MeterReadings, fees: CalcTarrifs, eletricityRateNumber: number): number {
  const hotWater = meterReadings.hotWater.current - meterReadings.hotWater.previous
  const hotWaterTotal = hotWater * fees.hotWater

  const coldWater = meterReadings.coldWater.current - meterReadings.coldWater.previous
  const coldWaterTotal = coldWater * fees.coldWater

  const drainage = (coldWater + hotWater) * fees.drainage

  let eletricityTotal = 0
  if (eletricityRateNumber === 1) {

  } else if (eletricityRateNumber === 2) {

  } else if (eletricityRateNumber === 3) {
    const fee = fees.eletricity.fee3
    const eletricityT1 = meterReadings.electricity.t1.current - meterReadings.electricity.t1.previous
    const eletricityT2 = meterReadings.electricity.t2.current - meterReadings.electricity.t2.previous
    const eletricityT3 = meterReadings.electricity.t3.current - meterReadings.electricity.t3.previous
    eletricityTotal = eletricityT1 * fee.t1 + eletricityT2 * fee.t2 + eletricityT3 * fee.t3
  }

  return Math.round(hotWaterTotal + coldWaterTotal + drainage + eletricityTotal)
}

function selectFees({cookerType, tariffs}: {cookerType: 'gas' | 'eletricity', tariffs: Tarrifs}) {
  const {fees} = tariffs
  const {gasCooker, electricCooker, ...restFees} = fees
  return {
    ...restFees,
    eletricity: cookerType === 'gas' ? gasCooker : electricCooker
  }
}

export default Home
